name: 'NPM Publish - Package Publishing Automation'
# This workflow automates npm package publishing to unlock GitHub package publishing badges
# Triggers on:
# 1. New releases (tags starting with 'v')
# 2. Manual dispatch for testing
# 3. Push to main branch (for package verification)
on:
  # Trigger on new releases
  release:
    types: [published]
  
  # Allow manual trigger for testing
  workflow_dispatch:
    inputs:
      publish_type:
        description: 'Type of publish'
        required: true
        default: 'dry-run'
        type: choice
        options:
          - 'dry-run'
          - 'publish'
  
  # Trigger on push to main branch for verification
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'src/**'
      - 'lib/**'
      - 'index.js'

# Set environment variables
env:
  NODE_VERSION: '20.x'
  NPM_REGISTRY: 'https://registry.npmjs.org/'

# Define jobs
jobs:
  # Job 1: Package Quality Checks
  quality-checks:
    name: 'Quality Checks & Testing'
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: 'Setup Node.js Environment'
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: ${{ env.NPM_REGISTRY }}
      
      - name: 'Install Dependencies'
        run: |
          echo "📦 Installing project dependencies..."
          npm ci
      
      - name: 'Run Quality Checks'
        run: |
          echo "🔍 Running package quality checks..."
          npm run lint || echo "⚠️ Linting not configured"
          npm test || echo "⚠️ Tests not configured"
      
      - name: 'Package Verification'
        run: |
          echo "📋 Verifying package configuration..."
          npm pack --dry-run
          echo "✅ Package structure validated"

  # Job 2: NPM Publishing
  npm-publish:
    name: 'NPM Package Publishing'
    runs-on: ubuntu-latest
    needs: quality-checks
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_type == 'publish')
    
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: 'Setup Node.js Environment'
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: ${{ env.NPM_REGISTRY }}
      
      - name: 'Install Dependencies'
        run: |
          echo "📦 Installing dependencies for publishing..."
          npm ci
      
      - name: 'Package Information'
        run: |
          echo "📋 Package Information:"
          echo "Name: $(npm pkg get name | tr -d '"')"
          echo "Version: $(npm pkg get version | tr -d '"')"
          echo "Registry: ${{ env.NPM_REGISTRY }}"
      
      - name: 'Check Package Existence'
        id: check-package
        run: |
          echo "🔍 Checking if package version exists..."
          PACKAGE_NAME="@galafis/github-achievement-unlocker"
          PACKAGE_VERSION=$(npm pkg get version | tr -d '"')
          
          # Check if package version already exists
          if npm view $PACKAGE_NAME@$PACKAGE_VERSION version 2>/dev/null; then
            echo "⚠️ Package version $PACKAGE_VERSION already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "✅ Package version $PACKAGE_VERSION is available for publishing"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: 'Publish to NPM with Retry Logic'
        if: steps.check-package.outputs.exists == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "🚀 Publishing @galafis/github-achievement-unlocker to NPM..."
          
          # Retry configuration
          MAX_RETRIES=3
          RETRY_DELAY=10
          
          for i in $(seq 1 $MAX_RETRIES); do
            echo "📤 Publishing attempt $i of $MAX_RETRIES..."
            
            if npm publish --access public; then
              echo "✅ Package published successfully!"
              echo "🎉 @galafis/github-achievement-unlocker is now available on NPM"
              exit 0
            else
              EXIT_CODE=$?
              echo "❌ Publishing attempt $i failed with exit code $EXIT_CODE"
              
              # Check for specific error codes
              if [ $EXIT_CODE -eq 404 ]; then
                echo "🔍 Error E404: Package or registry not found"
                echo "💡 Diagnostics: Checking registry connectivity..."
                npm ping
                npm whoami
              elif [ $EXIT_CODE -eq 409 ]; then
                echo "🔍 Error E409: Package version conflict"
                echo "💡 This version may already exist or be in conflict"
                npm view @galafis/github-achievement-unlocker versions --json
              fi
              
              if [ $i -lt $MAX_RETRIES ]; then
                echo "⏳ Waiting ${RETRY_DELAY}s before retry..."
                sleep $RETRY_DELAY
              fi
            fi
          done
          
          echo "💥 All publishing attempts failed after $MAX_RETRIES retries"
          exit 1
      
      - name: 'Post-Publish Verification'
        if: steps.check-package.outputs.exists == 'false'
        run: |
          echo "🔍 Verifying published package..."
          sleep 30  # Wait for NPM registry propagation
          
          PACKAGE_VERSION=$(npm pkg get version | tr -d '"')
          if npm view @galafis/github-achievement-unlocker@$PACKAGE_VERSION version; then
            echo "✅ Package verification successful!"
            echo "🌐 Package URL: https://www.npmjs.com/package/@galafis/github-achievement-unlocker"
          else
            echo "⚠️ Package verification failed - may need time to propagate"
          fi
      
      - name: 'Skip Publishing (Version Exists)'
        if: steps.check-package.outputs.exists == 'true'
        run: |
          echo "ℹ️ Skipping publish - package version already exists on NPM"
          echo "📋 Current published version matches local version"

  # Job 3: Dry Run Simulation
  dry-run:
    name: 'Dry Run Simulation'
    runs-on: ubuntu-latest
    needs: quality-checks
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.publish_type == 'dry-run'
    
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v5
      
      - name: 'Setup Node.js Environment'
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: ${{ env.NPM_REGISTRY }}
      
      - name: 'Install Dependencies'
        run: npm ci
      
      - name: 'Simulate Publishing'
        run: |
          echo "🧪 Simulating NPM publish for @galafis/github-achievement-unlocker..."
          npm publish --dry-run
          echo "ℹ️ This was a simulation - no actual publishing occurred"
